name       : skopeo
version    : 0.1.39
release    : 1
source     :
    - git|https://github.com/containers/skopeo : v0.1.39
    # we need these extra sources so we can grab configs to package them
    # these are vendored with skopeo but are missing configs we need
    # lookup correct versions in go.mod
    - git|https://github.com/containers/image : v3.0.1
    - git|https://github.com/containers/storage : v1.13.0
license    : Apache-2.0
component  : virt
summary    : Work with remote OCI images registries - retrieving information, images, signing content
description: |
    Skopeo works with API V2 registries such as Docker registries, the Atomic registry, private registries, local directories and local OCI-layout directories. Skopeo does not require a daemon to be running to perform these operations.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gpgme)
    - pkgconfig(ostree-1)
    - btrfs-progs-devel
    - golang
    - go-md2man
environment: |
    export BUILDTAGS="containers_image_ostree_stub ostree"
build      : |
    %make binary-local BUILDTAGS="$BUILDTAGS"
    %make docs
install    : |
    %make_install

    install -m644 $sources/storage.git/storage.conf -t "$installdir/etc/containers/"
    install -m644 $sources/image.git/registries.conf -t "$installdir/etc/containers/"
    %patch -d $installdir/etc/containers/ < $pkgfiles/registries.conf.patch

    install -d "$installdir/usr/share/man/man5/"
    go-md2man -in "$sources/storage.git/docs/containers-storage.conf.5.md" -out "$installdir/usr/share/man/man5/containers-storage.conf.5"
    go-md2man -in "$sources/image.git/docs/containers-registries.conf.5.md" -out "$installdir/usr/share/man/man5/containers-registries.conf.5"
    go-md2man -in "$sources/image.git/docs/containers-policy.json.5.md" -out "$installdir/usr/share/man/man5/containers-policy.conf.5"
