name       : skopeo
version    : 1.2.0
release    : 9
source     :
    - git|https://github.com/containers/skopeo : v1.2.0
    # we need these extra sources so we can grab configs to package them
    # these are vendored with skopeo but are missing configs we need
    - git|https://github.com/containers/image : v5.6.0
    - git|https://github.com/containers/storage : v1.23.5
    - git|https://github.com/containers/common : v0.22.0
license    : Apache-2.0
component  : virt
summary    : Work with remote OCI images registries - retrieving information, images, signing content
description: |
    Skopeo works with API V2 registries such as Docker registries, the Atomic registry, private registries, local directories and local OCI-layout directories. Skopeo does not require a daemon to be running to perform these operations.
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(gpgme)
    - btrfs-progs-devel
    - golang
    - go-md2man
build      : |
    %make bin/skopeo
    %make docs
install    : |
    %make_install

    install -m644 $sources/storage.git/storage.conf -t "$installdir/etc/containers/"
    install -m644 $sources/image.git/registries.conf -t "$installdir/etc/containers/"
    install -m644 $sources/common.git/pkg/config/containers.conf -t "$installdir/etc/containers/"
    %patch -d $installdir/etc/containers/ < $pkgfiles/registries.conf.patch
    %patch -d $installdir/etc/containers/ < $pkgfiles/containers.conf.patch

    install -d "$installdir/usr/share/man/man5/"
    go-md2man -in "$sources/storage.git/docs/containers-storage.conf.5.md" -out "$installdir/usr/share/man/man5/containers-storage.conf.5"
    go-md2man -in "$sources/image.git/docs/containers-registries.conf.5.md" -out "$installdir/usr/share/man/man5/containers-registries.conf.5"
    go-md2man -in "$sources/image.git/docs/containers-policy.json.5.md" -out "$installdir/usr/share/man/man5/containers-policy.conf.5"
    go-md2man -in "$sources/common.git/docs/containers.conf.5.md" -out "$installdir/usr/share/man/man5/containers.conf.5"
